const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.querySelector('[data-year]').textContent=new Date().getFullYear();
const reveals=document.querySelectorAll('.reveal');
if(reduced||!('IntersectionObserver'in window))reveals.forEach(x=>x.classList.add('visible'));else{const o=new IntersectionObserver((es,ob)=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ob.unobserve(e.target)}}),{rootMargin:'0px 0px -7%',threshold:.08});reveals.forEach(x=>o.observe(x))}
const header=document.querySelector('[data-header]'),progress=document.querySelector('[data-progress]');
function scrollUI(){header.classList.toggle('scrolled',scrollY>24);const d=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${d>0?scrollY/d:0})`}scrollUI();addEventListener('scroll',scrollUI,{passive:true});
const projects={
blend:{index:'01',mark:'BL',type:'Private social product',status:'In development',title:'Blend',description:'A two-person experience for comparing YouTube tastes through separate, read-only account connections and a shared guided reveal.',tags:['React','TypeScript','FastAPI','MongoDB','OAuth 2.0'],focus:'Consent, privacy, and shared discovery',link:'https://github.com/tanmayhutt/blend'},
thwip:{index:'02',mark:'TH',type:'Developer tool',status:'Open source',title:'Thwip',description:'A terminal interface for discovering local coding agents, switching providers mid-project, and carrying completed conversation context across tools.',tags:['Python','Terminal UI','Agent tooling'],focus:'Continuity across local coding agents',link:'https://github.com/tanmayhutt/thwip-cli'},
server:{index:'03',mark:'AS',type:'Infrastructure',status:'Self-hosted',title:'Arch server',description:'An old Lenovo laptop repurposed as a headless Arch Linux node for private storage, remote administration, and zero-port public web delivery.',tags:['Arch Linux','Docker','Cloudflare','Tailscale'],focus:'Private infrastructure from old hardware',link:'https://github.com/tanmayhutt/arch-server'},
filmedin:{index:'04',mark:'FI',type:'Full-stack application',status:'Deployed',title:'FilmedIn',description:'A place for movie and television fans to track media, build playlists, and generate wallpapers, with authentication and a full deployment.',tags:['React','Express','MongoDB','TMDB'],focus:'Personal media tracking and discovery',link:'https://github.com/tanmayhutt/FilmedIn'},
wifisense:{index:'05',mark:'WS',type:'Embedded experiment',status:'Prototype',title:'WiFiSense',description:'ESP8266 firmware exploring room-presence detection through changes in Wi-Fi signal strength and layered statistical filtering.',tags:['C++','ESP8266','Signal processing'],focus:'Sensing presence without cameras',link:'https://github.com/tanmayhutt/WiFiSense'}};
const visual=document.querySelector('[data-project-visual]'),fields={index:document.querySelector('[data-visual-index]'),mark:document.querySelector('[data-visual-mark]'),type:document.querySelector('[data-project-type]'),status:document.querySelector('[data-project-status]'),title:document.querySelector('[data-project-title]'),description:document.querySelector('[data-project-description]'),tags:document.querySelector('[data-project-tags]'),focus:document.querySelector('[data-project-focus]'),link:document.querySelector('[data-project-link]')};
function select(key,focus=false){const p=projects[key];if(!p)return;visual.dataset.projectVisual=key;for(const [k,e]of Object.entries(fields))if(!['tags','link'].includes(k))e.textContent=p[k];fields.tags.replaceChildren(...p.tags.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));fields.link.href=p.link;document.querySelectorAll('[data-project]').forEach(t=>t.setAttribute('aria-selected',t.dataset.project===key));if(focus)document.querySelector(`[data-project="${key}"]`).focus()}
const tabs=[...document.querySelectorAll('[data-project]')];tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>select(tab.dataset.project));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[n].dataset.project,true)})});
if(!reduced){document.querySelectorAll('.card').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',`${e.clientX-r.left}px`);card.style.setProperty('--my',`${e.clientY-r.top}px`)}));document.querySelectorAll('[data-magnetic]').forEach(el=>{el.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.07}px,${(e.clientY-r.top-r.height/2)*.07}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const dialog=document.querySelector('[data-command]'),openDialog=()=>{if(!dialog.open)dialog.showModal()},closeDialog=()=>{if(dialog.open)dialog.close()};document.querySelector('[data-command-open]').onclick=openDialog;document.querySelector('[data-command-close]').onclick=closeDialog;dialog.onclick=e=>{if(e.target===dialog)closeDialog()};dialog.querySelectorAll('a').forEach(a=>a.onclick=closeDialog);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();dialog.open?closeDialog():openDialog()}if(dialog.open&&!e.metaKey&&!e.ctrlKey){const map={w:'#work',p:'#practice',a:'#about',r:'https://tanmaytiwari.me/resume/',e:'mailto:tiwaritanmay1021@gmail.com'},target=map[e.key.toLowerCase()];if(target){e.preventDefault();closeDialog();target[0]==='#'?document.querySelector(target).scrollIntoView():window.open(target,target.startsWith('mailto:')?'_self':'_blank')}}});
